### ISSUE TITLE
Remove the logo from the readme.md for the time being

### ISSUE THREAD

**Issue by ExperiencersInternational** [RobloxStatusLive/rsl#1]
As some Roblox developers pointed out, I'm a complete idiot, and the branding for Roblox Status Live should be removed since it potentially takes Roblox's intellectual property.

I'm asking for this to be done quickly.

**Comment by Crcoli7307** [comment]
Hey there! We will get to work on this.

**Comment by Crcoli7307** [comment]
Removed from README.md

Will change on website and DevForum thread once new logo is released.
