### ISSUE TITLE
You are violating Roblox copyright & logo guidelines

### ISSUE THREAD

**Issue by Starnamics** [RobloxStatusLive/rsl#5]
Your Logo & Name violates Roblox’s [Name and Logo guidelines](https://en.help.roblox.com/hc/en-us/articles/115001708126-Roblox-Name-and-Logo-Community-Usage-Guidelines)

You violate both guideline 4 & 5

4 because you are using the name “Roblox” in your brands name. (this is not allowed for apps/websites unless the website is a fan website)
5 because you have modified the Roblox logo & are using it in your brands logo.

I also believe in the Github for Roblox Status Live, it claims that [@GamersInternational](https://devforum.roblox.com/u/gamersinternational) owns the rights to the logo, however this is not true as they had just modified Roblox’s logo, which is copyright infringement.

I suggest rebranding both your name & logo or you may get into some legal trouble with Roblox.

**Comment by TyNoOutlet** [comment]
I agree the name and logo use is in violation. I'd also like to add something: they don't own copyright on this, and @GamersInternational doesn't own IP rights to the logo. The project's open-sourced, you can't claim copyright but then use the MIT license and publish it on GitHub.

**Comment by Crcoli7307** [comment]
Already working on another logo, the RSL name will remain unchanged.
